---
- name: Add ppa:ondrej/php
  apt_repository:
    repo: ppa:ondrej/php

- name: Install PHP Packages
  apt:
    state: present
    force_apt_get: yes
    pkg:
      - composer
      - php-imagick
      - php-memcached
      - php-redis
      - php-xdebug
      - php-dev
      - php7.4
      - php7.4-bcmath
      - php7.4-bz2
      - php7.4-cgi
      - php7.4-cli
      - php7.4-common
      - php7.4-curl
      - php7.4-dba
      - php7.4-dev
      - php7.4-enchant
      - php7.4-fpm
      - php7.4-gd
      - php7.4-gmp
      - php7.4-imap
      - php7.4-interbase
      - php7.4-intl
      - php7.4-json
      - php7.4-ldap
      - php7.4-mbstring
      - php7.4-mysql
      - php7.4-odbc
      - php7.4-opcache
      - php7.4-pgsql
      - php7.4-phpdbg
      - php7.4-pspell
      - php7.4-readline
      - php7.4-snmp
      - php7.4-soap
      - php7.4-sqlite3
      - php7.4-sybase
      - php7.4-tidy
      - php7.4-xml
      - php7.4-xmlrpc
      - php7.4-xsl
      - php7.4-zip

- include_tasks: setup-cli-php-ini.yml
- include_tasks: setup-fpm-php-ini.yml
- include_tasks: setup-extensions.yml





